### ISSUE TITLE
How and where is the stylesheet that i need to include so it works on all the pages where the editor has saved the data

### ISSUE THREAD

**Issue by SimonJ** [vueup/vue-quill#68] opened 2021-08-17 10:22 UTC
This is what i get out from my database when i have saved content from the editor. but there is no stylesheet to style the classes

![Skærmbillede 2021-08-17 kl  12 21 11](https://user-images.githubusercontent.com/183790/129709453-184ec618-4914-45e1-a74d-e7642bfa5249.png)

**Comment by MattSala** [comment] 2021-09-17 14:00
I believe that the issue is similiar to the one below and the problem is that the VueQuill doesn't support the Quill's CSS inline styling yet. 
[Quill documentation](https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline)
I would love if someone from the team could shed some light on the topic and told us if it's planned in the future releases, because it seems to be a dealbreaker for a lot of people.
Duplicate of #66

**Closed** 2022-07-23 06:42 UTC
Labels: wontfix
